FROM resin/rpi-raspbian:jessie

RUN apt-get update && apt-get install -y \
    git

RUN mkdir /opt/vc && mkdir /opt/vc/bin

COPY /opt/vc/lib /opt/vc/lib/

RUN git clone https://github.com/silvanmelchior/RPi_Cam_Web_Interface.git
COPY config.txt RPi_Cam_Web_Interface/
RUN cd RPi_Cam_Web_Interface && pwd && chmod u+x *.sh && ./install.sh q

CMD ls -ahl .
